### ISSUE TITLE
Best way to remove cell from UICollectionView

### ISSUE THREAD

**Issue by johanrydenstam** [facebook/componentkit#149]
I'm trying to create a UICollectionView where each cell has a delete button. When the button is clicked the cell should be removed.

The UICollectionViewController knows which model that should be removed. But how can I know at which indexPath the model is represented? The ```CKCollectionViewDataSource```doesn't provide a method for enumerating the models. ```CKComponentDataSource``` does, and ```CKCollectionViewDataSource```wraps that class. It would be possible if ```CKCollectionViewDataSource```exposed it's wrapped data source.

How should this be done? Do I need to switch data source?

**Comment by aaronschubert0** [comment]
Do this, inside `- (void)collectionView:(UICollectionView *)collectionView didSelectItemAtIndexPath:(NSIndexPath *)indexPath`:
```
    NSObject *object = [_dataSource modelForItemAtIndexPath:indexPath];
    CKArrayControllerInputItems items;
    items.remove(indexPath);
    [_dataSource enqueueChangeset:{{}, items}
                                  constrainedSize:[_sizeRangeProvider sizeRangeForBoundingSize:_collectionView.bounds.size]];
```
`_dataSource` is the `CKCollectionViewDataSource` object

**Comment by johanrydenstam** [comment]
Thanks, but I don't wan't the entire cell to trigger the delete behaviour, rather just a delete button.

**Comment by smiLLe** [comment]
in theory  (though i never tried)
- create nsarray of your models in your VC (ViewController)
- pass your VC as a weak property in the context object to your DataSource
- let the VC respond to a selector / use a protocol ( -deleteModelWithId:)
- enqueue your models to fill your (ListView)
- press the delete button in your component, call context.vc.deleteModelWithId:
- deleteModelWithId removes model with given ID in the array
- since you know the index in the array of the removed model you can enqueue a changeset as @aaronschubert0 mentioned

**Comment by johanrydenstam** [comment]
Alright, in that case it seems more appropriate to create a custom data source. I don't want to keep an array with my models since the ```CKCollectionViewDataSource```already does exactly that.

My current workaround is to expose the wrapped ```CKComponentDataSource```with key value coding, since it's impossible to subclass ```CKCollectionViewDataSource```.

Is there a reason why the wrapped datasource isn't exposed?

**Comment by smiLLe** [comment]
I don't know. Unfortunately it seems like the guys from facebook are very busy right now, so don't expect a fast answer :(

**Comment by aaronschubert0** [comment]
Can you not use CKButtonComponent for the delete area and then send that action back up to the controller and process it there?

Aaron

**Comment by benlodotcom** [comment]
> Is there a reason why the wrapped data source isn't exposed?

The fact that the datasource internally keeps an array with the models (and other things) corresponding to the input state is merely an implementation detail. This is only used for internal bookkeeping and that's why we are not exposing it. What is exposed is what the CV needs (the output state). 
The responsibility of computing the right changeset (which requires some bookkeeping of the data) is left to the user of the datasource.

The solution that @smiLLe proposed is spot on on what should be done.

**Comment by dylanslewis** [comment]
Has anyone else had experience with - (void)dataSource:(CKCollectionViewDataSource *)dataSource didSelectItemAtIndexPath:(NSIndexPath *)indexPath not being called?

This is preventing us from passing information obtained from the touched component cell.

**Comment by aaronschubert0** [comment]
@dylanslewis this should really be a separate issue but it can be because your CKText/Label components are blocking the touch, which is what they do by default. You can override this in their view attributes.

**Comment by dylanslewis** [comment]
Thanks @aaronschubert0, unfortunately that wasn't the problem. I've opened a new issue here: https://github.com/facebook/componentkit/issues/271
