### ISSUE TITLE
Question - scaleToDisappear for previous component

### ISSUE THREAD

**Issue by DrChrispoper** [facebook/componentkit#158]
In the docs and example you shows a way to animate the overlay when appearing.
http://componentkit.org/docs/animation.html#animationsfrompreviouscomponent

I was wondering if it was possible to have an animation to make it disappear with something like this:

```
- (std::vector<CKComponentAnimation>)animationsFromPreviousComponent:(EmailComponent *)previousComponent
{
    if (previousComponent->_overlay == nil && _overlay != nil) {
        return {{_overlay, scaleToAppear()}}; // Scale the overlay in when it appears.
    } else {
        return {{previousComponent->_overlay, scaleToDisappear()}};
    }
}
```

I tried but the animation is not called. 
Is there something I am missing or is this something not supported yet?

**Comment by adamjernst** [comment]
No, it's not easy because the view is hidden by Components as soon as it's no longer present in the component hierarchy.

Here's how we work around this at Facebook:

- Instead of using the `CAAnimation` constructor for `CKComponentAnimation`, use the constructor that takes a `CKComponentAnimationHooks` structure containing blocks.
- In the `willRemount` block, call `-snapshotViewAfterScreenUpdates:NO` on the component's current `viewForAnimation` property. Return that view from the block.
- In the `didRemount` block, you'll receive the view as the `context` parameter (since it was returned by the previous block). Now you can insert the view into the hierarchy (positioning it correctly will be a little tricky) and fade it out.
- In `cleanup`, remove the snapshot view from the hierarchy.

Make sense?

**Comment by DrChrispoper** [comment]
Thanks.
Do you mean something like this?
```
static CKComponentAnimationHooks *scale(CKComponent *component, CAAnimation *originalAnimation)
{
    CKCAssertNotNil(component, @"Component being animated must be non-nil");
    CKCAssertNotNil(originalAnimation, @"Animation being added must be non-nil");
    
    // Don't mutate the animation the component returned, in case it is a static or otherwise reused. (Also copy
    // immediately to protect against the *caller* mutating the animation after this point but before it's used.)
    CAAnimation *copiedAnimation = [originalAnimation copy];
    
    return {
        .willRemount = ^(){
            return [component.viewForAnimation snapshotViewAfterScreenUpdates:NO];
        },
        .didRemount = ^(id context){
            CALayer *layer = component.viewForAnimation.layer;
            CKCAssertNotNil(layer, @"%@ has no mounted view, so it cannot be animated", [component class]);
            //things
        },
        .cleanup = ^(CCMAppliedAnimationContext *context){
            [context.targetLayer removeAnimationForKey:context.key];
        }
    };
}
```

If so I'm having an error at the return "Excess elements in scalar initializer" as if my blocks are not correct. Is there something I'm missing out?

**Comment by DrChrispoper** [comment]
It works thanks!

**Comment by dbworku** [comment]
@adamjernst  @DrChrispoper does this still work? 

I tried pass a snapshot of the previous component's view with `snapshotViewAfterScreenUpdates:NO` in the `willRemount` block. However, both the `viewContext` and `viewForAnimation` on the component are `nil`.
