### ISSUE TITLE
Why CKCollectionViewDataSource not public "enqeueReload" method

### ISSUE THREAD

**Issue by keywind** [facebook/componentkit#213]
CKCollectionViewDataSource Only has 

`- (void)updateContextAndEnqeueReload:(id)newContext;`

without newContext, it will not reload. But all my data is in model and the context is nil

**Comment by benlodotcom** [comment]
I'm not entirely opposed to exposing it but enqueueReload does not take any new models or sizes so it will affect your tree only if it's dependent on some global mutable state (i.e your component tree is not entirely a pure function of the model).

What is your use case exactly ?

We use this API internally at FB on accessibility change so that we reload all the components and have the right accessibility attributes recomputed. This is handled by a wrapper around the CKComponentDataSource, this is why it is exposed publicly there but not upper.

**Comment by keywind** [comment]
In my case, I didn't use context but my models changed. 
I think I can ignore which model changed and just reload the entire component tree. ComponentKit would  only update the necessary elements, right?

**Comment by adamjernst** [comment]
It is public on `CKTransactionalComponentDataSource` and will be on its corresponding collection view data source, so I'm going to close this and say that it'll be fixed once we complete the transition to it.
