### ISSUE TITLE
Swift support

### ISSUE THREAD

**Issue by Fab1n** [facebook/componentkit#22]
Hey guys, 

this project made me really feel happy while watching the video. I really like the concept of declarative style and thus love React. 
I am really excited and will really try it out the next days. 

While watching the video I thought "oh how cool, this is like it needed swift as language. Because immutability... this is so much swift like". I thought, how would I implement it in swift. Then at the end of the video you got me!!!

Any timeline or news working on swiftifieing this thing?

**Comment by wczekalski** [comment]
@Fab1n I am pretty excited for Components because my production code is mainly written in objc. 
The reality is though, that we shouldn't swiftify this thing, because Swift gives us an opportunity to create something much better IMO

**Comment by Isuru-Nanayakkara** [comment]
+1 for Swift support. I think they even mentioned something about porting it to Swift in the @Scale talk. I'm not sure.

**Comment by Fab1n** [comment]
sure, they mentioned it. That's why I wrote this issue for :). Peek to the last minute of the video of the talk and you hear the swift mention.

**Comment by nheagy** [comment]
Adam mentioned swift is on hold for a bit on twitter: https://twitter.com/adamjernst/status/580955735456010242

I think C++ have some important similarities as far as API design goes, so even though a swift/objC wrapper is probably not viable the final API should be very familiar.

**Comment by modocache** [comment]
I'm super interested in exploring using ComponentKit from Swift! It should be possible by building an intermediate bridging layer in Objective-C. I'd love to see some proof-of-concepts--maybe submit a pull request?

**Comment by grp** [comment]
I think @arigrant looked into what a Swift API might look like, could be a good starting place before writing an implementation/bridge.

**Comment by adamjernst** [comment]
I should also mention [Few.swift](https://github.com/joshaber/Few.swift) as a project that's already exploring a reactive model in Swift. It's not asynchronous and is still experimental, but I think it's promising.

**Comment by danscan** [comment]
Any update on this?  To be able to use ComponentKit with Swift would be HUGE.

**Comment by S0r13n** [comment]
+1 for Swift support.

**Comment by metabren** [comment]
+1

**Comment by schickling** [comment]
:+1:

**Comment by 3a4oT** [comment]
+1

**Comment by choidamdam** [comment]
+1

**Comment by sdduursma** [comment]
+1

**Comment by jlnbuiles** [comment]
+1

**Comment by anton-matosov** [comment]
+1

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by adly-holler** [comment]
+1

**Comment by darknoon** [comment]
Hey, it's probably fair to give an explanation of why this isn't going to happen in the short term:

Without ObjC++ interoperability in Swift it will be *really* hard to make this work well. ObjC++ and Swift are pretty similar, but have incompatible object models. It would take a lot of work to make C++ compatibility happen in Swift: until we have an elegant interoperation mode at the compiler level, we can’t support Swift in this ObjC++ framework.

I'm interested in what features of Swift this community is excited about, and see what we can do to help bring those ideas to ComponentKit-based apps. Many of the nice things we love about Swift are already in C++. It, like Swift, is in active development—C++14 and C++17 has many new features. For example, a proposal for [async/await like in c#/hack](https://paoloseverini.wordpress.com/2014/04/22/async-await-in-c/).

So, here’s what it would take to support Swift today with the existing compiler landscape: wrap all of the C++ code in pure ObjC. This undermines the elegance we have with `CKComponentViewConfiguration` etc where you can declare things inline, and degrade performance by creating a bunch more ObjC objects.

I think the best way to achieve what you're looking for would be to port the _ideas_ from ComponentKit / React over to Swift. We're happy to help with any questions you might have in doing that, but it's not on our priority list right now since there is so much to do improving ComponentKit as an ObjC++ framework. For instance, I recently worked on memoization for components and layouts (using some cool C++ features), which should make ComponentKit even more efficient and scale to really hard UI problems.

I think the closest thing to what you guys are looking for is [Few.swift](https://github.com/joshaber/Few.swift). My understanding is that it's still pretty early on and not ready for production, but you should contribute!

One final thing I'll mention is AsyncDisplayKit, which _is_ compatible with Swift: https://github.com/facebook/asyncdisplaykit. There are some features like stack layouts similar to ComponentKit there, though it's closer to UIKit than React. It trades off the easy updates inherent in the React model for easier UIView manipulation and gestures.

Hope that helps, and sorry to be bringer of bad news… :/

**Comment by zackshapiro** [comment]
Any updates on Swift support for ComponentKit?

**Comment by eczarny** [comment]
@zackshapiro I believe much of what @darknoon talks about from his comment in 2015 still applies here, unfortunately. Last I checked Swift still doesn't work with Objective-C++ and implementing a pure Objective-C wrapper API would take considerable effort.

/cc @ocrickard

**Comment by leavez** [comment]
Hey guys, I write a simple wrapper of componentKit for swift, [ComponentSwift](https://github.com/leavez/ComponentSwift). Please have a try if interested.
