### ISSUE TITLE
possible CATransaction issue

### ISSUE THREAD

**Issue by stampsrule** [facebook/componentkit#235]
I don't know where the issue could be coming from but I am getting multiple console lines of 
```Objective-C++
+[CATransaction synchronize] called within transaction
```

**Comment by adamjernst** [comment]
Hm, I'd need more info. There aren't any callsites to `+synchronize` inside ComponentKit.

**Comment by darknoon** [comment]
Could you try setting a symbolic breakpoint on +[CATransaction synchronize] and post the stack trace? It would be helpful to know what you're doing with regard to threading.

**Comment by stampsrule** [comment]
I have nothing in my code that is +[CATransaction synchronize]  or CATransaction synchronize and the only CATransaction is in componentkit

**Comment by ocrickard** [comment]
CKAsyncLayer definitely uses some async transactions and *could* be at fault here if it has a bad interaction with something.

**Comment by ocrickard** [comment]
@stampsrule can you please provide a stack trace with the symbolic breakpoint?  Just because you don't explicitly use CATransaction doesn't mean that UIKit isn't implicitly creating them for you, particularly with UITableView and UICollectionView.

**Comment by stampsrule** [comment]
I tried to find the place to put the breakpoint, but when I commented out the place appearing to cause the CATransaction issue out the CATransaction issue was still created.  is there another way to insert the breakpoint? the app is not crashing just displaying the message.

**Comment by ocrickard** [comment]
@stampsrule you can follow the guide here:

https://developer.apple.com/library/ios/recipes/xcode_help-breakpoint_navigator/articles/adding_a_symbolic_breakpoint.html

Basically in Xcode you use the "+" button in the breakpoints navigator, select Symbolic Breakpoint, and then enter "+[CATransaction synchronize]" in the textbox.

**Comment by stampsrule** [comment]
here are the 2 stack traces
![screen shot 2015-06-09 at 2 32 10 pm](https://cloud.githubusercontent.com/assets/1462834/8068956/92cae9d2-0eb4-11e5-8cb9-c77ad5f35824.png)

![screen shot 2015-06-09 at 2 32 35 pm](https://cloud.githubusercontent.com/assets/1462834/8068957/92ce2aac-0eb4-11e5-9705-2eee1e5b5959.png)

**Comment by ocrickard** [comment]
Yep, these are UIKit calls to CATransaction synchronize, not ComponentKit.  I don't believe this is related to usage of ComponentKit, but since we're here...

Based on these, here's my theory on what's going on (speculation, may not be right):

1. You have something on your main thread that is opening a CATransaction.  This commonly occurs in the update block of a collection view or within the beginUpdates/endUpdates function on a UITableView.
2. One of your existing data processing stages is somehow using a CATransaction to do non-UI-related work.  (I suspect the NSAttributedString category you're using to generate a string from HTML is responsible from the stack traces you posted).
3. If 2 occurs before 1 completes, then you would probably end up with this log statement.

My guess on how to fix: I would try pulling that data processing out and doing it at a different point in time.
