### ISSUE TITLE
Model, State, Context, Scope more detailed explanation is needed

### ISSUE THREAD

**Issue by PaulTaykalo** [facebook/componentkit#239]
There are four main object we're working here, which are needed to work with ComponentKit  

- Model  (The data that is needed to be rendered in some way by components)  
- State  (Information that is not from model, but, also represents component state). View layer, which doesn't need to be represented on model layer.
- Context (... ?) (Some high-level data, that isn't related to the model, but can provide additional data how to present components views(i.e. Short-List/Long-List/Detailed list/ etc))
- Scope (...?)    

Moar examples with explanation are needed :)

**Comment by ocrickard** [comment]
Your explanations of these objects are correct. Seems the only one that is unclear is scope, which we have documentation here:

http://componentkit.org/docs/scopes.html

Here's an excerpt from an internal doc I wrote on scopes. We'll be publishing more on these subjects in the near future.

## Scopes

Cool, so a CKComponentController is the mutable partner for a CKComponent that manages persistent interactions with other systems and frameworks. One of the deep dark mysteries (I kid) of component kit is how we know that a specific component corresponds with an existing controller. After all it's not like the old components explicitly pass the controller along to the newer generations. Instead, this linkage is implicitly managed by a scope which uniquely identifies a component in its component tree.

As components are constructed, a mirrored tree of scopes is built. These scopes have a root, which owns the tree. At each level, as a component constructor builds a scope, it checks the previous version of the tree to see if this component should be associated with a previously-generated component.  

One of the questions we like to ask in interviews is find node in clone, where the interviewee is asked to find a corresponding view in a mirrored view hierarchy. This is a similar conceptual problem, except instead of relying on indices and building an index path, scopes are identified by a component class, and an optional identifier. Those of you who have run into a scope collision in components and had to add some sort of identifier were allowing the components infra to distinguish two sibling components that had the same class.  

Scopes are stack-allocated objects that retrieve a scope handle for the corresponding scope in the previous component tree. This handle is an objective-c object wrapper for the component controller. When the stack-allocated scope is initialized at the beginning of a component constructor, that scope pushes a frame onto a thread-local stack. Then inside the CKComponent initializer, we ask the top of the thread-local scope stack for its handle, which contains the associated controller.
