### ISSUE TITLE
How to use CKTextKitEntityAttribute with CKTextKitEntityAttributeName?

### ISSUE THREAD

**Issue by tranngoclinh88** [facebook/componentkit#243]
I just want to define some attributed strings to detect tap inside but do not have any example about it.
Could you please make a sample for it?

**Comment by MarcoSero** [comment]
You can use `NSDataDetector` to detect what you need (e.g. links) and then, after performing the detection, add the attribute `CKTextKitEntityAttributeName` to your attributed string for the detected ranges.

Something like this:

```objective-c
[linkDetector
 enumerateMatchesInString:attributedString.string
 options:0
 range:NSMakeRange(0, attributedString.string.length)
 usingBlock:^(NSTextCheckingResult *result, NSMatchingFlags flags, BOOL *stop) {
   NSURL *URL = [NSURL URLWithString:[attributedString.string substringWithRange:result.range]];
   [attributedString addAttribute:CKTextKitEntityAttributeName value:[[CKTextKitEntityAttribute alloc] initWithEntity:URL] range:result.range];
 }];
```

As a side note, be careful if you are caching `NSDataDetector` to save allocations, because it doesn't guarantee thread safety and components are generated in a background thread. I recommend using a background serial queue to do this kind of work.

**Comment by MarcoSero** [comment]
I agree that an example and more documentation would be nice.

**Comment by ocrickard** [comment]
Awesome, thanks answering this @MarcoSero!
