### ISSUE TITLE
Can't find a sample except collectionview

### ISSUE THREAD

**Issue by qiaoyan** [facebook/componentkit#260]
Is this suitable for a "normal" view at this point? like a segment on the top, a button at the bottom, a collectionview in the middle. Segment could chance collectionview's content. How to setup this viewcontroller?

**Comment by smiLLe** [comment]
What are you asking for? 
Replacing the CV's content after changing the segmentedControl's tab?
Setting the correct view order hierarchy for your segmentedControl, CV and button?

**Comment by grp** [comment]
For just showing a view with Components, you'll probably want `CKComponentHostingView` ([docs](http://componentkit.org/docs/component-hosting-view.html)) rather than the collection view setup. But there's still a question about integrating a collection view into the component hierarchy below the hosting view, since the data source is intended as a top level container for components. I don't know the answer for that part.

**Comment by darknoon** [comment]
You can make a component that has a subcomponent that makes a UICollectionView, that then contains components: totally possible.

I have something like that here: https://github.com/darknoon/componentkitx/blob/master/Examples/SimpleMacApp/SimpleMacApp/CKMSampleTableComponent.mm

You would just want to use the datasource that works with UICollectionView since that's is a Mac app using NSTableView.
