### ISSUE TITLE
Question: Design decisions and scope handling

### ISSUE THREAD

**Issue by nickfrey** [facebook/componentkit#295]
I have a tree where FooComponent contains BarComponent. FooComponent has a scope with a unique identifier, and BarComponent has a scope with an identifier of null. I have two siblings of FooComponent, each containing a BarComponent.

Here's the catch: I'm instantiating a BarComponent and passing it into the initializer of FooComponent. This causes a duplicate scope collision, presumably because BarComponent didn't enter the scope of FooComponent before it was created. Some sample code demonstrating this issue is below. 

My question is, what's the recommended pattern here if I would like BarComponent to be contained within FooComponent's scope? I considered passing a block to FooComponent that constructs a BarComponent and is called after FooComponent's scope has been configured, but ComponentKit discourages using blocks when possible because they can capture and hold on to local variables.

Thanks in advance.

```
@interface FooComponent : CKCompositeComponent @end
@interface BarComponent : CKComponent @end

@implementation FooComponent

+ (instancetype)newWithIdentifier:(NSString *)identifier child:(CKComponent *)child {
    CKComponentScope scope(self, identifier);
    return [super newWithComponent:child];
}

@end

@implementation BarComponent

+ (instancetype)new {
    CKComponentScope scope(self);
    return [super new];
}

@end
```

Then:

```
[CKStackLayoutComponent
  newWithView:{}
  size:{}
  style:{}
  children:{
     {[FooComponent newWithIdentifier:@"A" child:[BarComponent new]]},
     {[FooComponent newWithIdentifier:@"B" child:[BarComponent new]]}
  }
]]
```

Causes a collision on BarComponent's scope.

**Comment by adamjernst** [comment]
Yup! Great question. You can actually construct scopes outside of the components themselves, so there's no reason you couldn't do

```
BarComponent *a;
{
  CKComponentScope scope([BarComponent class], @"A");
  a = [BarComponent new];
}
BarComponent *b;
{
  CKComponentScope scope([BarComponent class], @"B");
  b = [BarComponent new];
}
... stack with the foo components here
```

This is a little clunky since bar component then probably shouldn't declare its own scope; but it does work. (I also don't like that it means more mutable local variables; you could extract it into a C function I suppose.)

However — is there any way to inject a new component that is above both the `FooComponent` and the `BarComponent`, perhaps? That is,

```
[CKStackLayoutComponent
  newWithView:{}
  size:{}
  style:{}
  children:{
     {[BazComponent newWithIdentifier:@"A"]},
     {[BazComponent newWithIdentifier:@"B"]}
  }
]]
```

Where `BazComponent` creates both `Foo` and `Bar`. It depends on your particular case I suppose.

This is somewhat related to the parent-child vs owner-ownee relationship in React. See [[Multiple Components]](https://facebook.github.io/react/docs/multiple-components.html) in the React docs, specifically the Ownership section.
