### ISSUE TITLE
Support a form of visibility: collapse

### ISSUE THREAD

**Issue by itsthejb** [facebook/componentkit#333]
Hi all,

Feature suggestion/question: I have a stack layout component that may in certain circumstances be constrained into a very small frame. The vertical stack consists of an image view and two stacked labels. The interesting point is that the first label is somewhat optional, and in these constrained conditions it would be fine to omit it completely. Since I can't know about the sizing context of the component when I create it there is (currently) no way to conditionally "remove" it. I could `flexShrink` this label, but then it would become clipped. What I want is that if the component can *shrink*, but that it should shrink to zero (collapse), instead.

This seems to be similar to [visibility: collapse](http://www.w3.org/TR/css3-flexbox/#visibility-collapse), although the intent is slightly different; rather than having this as an animatable property of the component, we would just apply this visibility in cases where we have a negative violation.

In any case, I thought I should raise this for ideas before potentially giving the implementation a shot in the next week or so.

Thanks!

PS. In a related note - due to use of TextKit directly, none of the text components have support for adjustable font sizes. Any thoughts on this? Generally speaking I think it's to be avoided, but there are situations when it can get you out of more complicated layout edge cases...

**Comment by itsthejb** [comment]
Initial experiment here: https://github.com/facebook/componentkit/compare/master...eyeem:flex-collapse?expand=1

**Comment by adamjernst** [comment]
Yep this is on our internal wishlist too! And thanks for doing the work to actually rough up an early implementation. That's always really helpful.

My main concern is that I don't want us to drift away from CSS flexbox. The main question I'd want answered is how this would be done in vanilla CSS/HTML. Looks like you've already done this somewhat by referencing `visibility: collapse` so I'll play around in a browser and see what it looks like.

**Comment by itsthejb** [comment]
Yep, all good. It crosses the line a little into AutoLayout territory... But that's not necessarily a bad thing. It certainly makes the layout more adaptive/dynamic. 

Another thought that came up when looking into this was, if you have more than one `flexCollapse` component, what should happen?

* Just collapse all of those. This is a bit of a blunt tool, but might be enough.
* Collapse under some kind of priority; but then things start getting a bit complicated...

In any case, I'll watch this space :+1:

**Comment by adamjernst** [comment]
Sorry for the long delay. I've totally drifted off and gotten busy with other stuff.

I'm still open to a pull request with behavior like this, but I'd want a good description of how you'd do something similar in CSS and how this approach diverges. (I honestly don't know CSS well enough to  even know for certain!)

Also, i do wish we had proper flex grow/shrink *factors* instead of just booleans. And our flex-shrink behavior is incorrect too… we shrink each element equally instead of proportionally to its size.

**Comment by itsthejb** [comment]
Gotcha on all counts. Sounds good, although since I found a workaround for the immediate use case I had for this, it's less likely I'll have much time to look into it. Perhaps this should be (potentially) rolled into the plan to rework grow/shrink factors?

In any case, leave open for now, I would suppose.

**Comment by ocrickard** [comment]
Since this is a year old at this point, and we didn't get to a conclusion here, Im gonna close this. We are focusing on improving our conformance with the flexbox standard, and this is possible through workarounds like custom layout components (though kinda ugly). We're open to more thoughts here, but conformance with flexbox is important to us, so looking forward to any more PR's on this topic that maintain conformance.
