### ISSUE TITLE
Q: State of CK

### ISSUE THREAD

**Issue by smiLLe** [facebook/componentkit#347]
Hey guys, 

i am curious if there are any plans for a new release? A lot of things have been changed since 0.12. 

I appreciate your hard work, thanks for this great framework :)

**Comment by MarcoSero** [comment]
I second that :+1: 
Especially since there is a pretty annoying bug in 0.12 that has been fixed in master https://github.com/facebook/componentkit/issues/202#issuecomment-123594634

**Comment by adamjernst** [comment]
Yes, we're overdue for a version bump! Will do asap.

**Comment by darknoon** [comment]
I don't think there's much of a semver process… those waiting for updates should probably just use master.

**Comment by grp** [comment]
Ha, yeah, this is a common for Cocoapods by FB. I'd generally agree with @darknoon in general about tracking master, since that's what we do internally, but I don't want to speak for the ComponentKit team. :)

**Comment by MarcoSero** [comment]
> those waiting for updates should probably just use master

You're probably right, but I've been bitten too many times by using a pod on master that now if can avoid I'll do it :)

**Comment by darknoon** [comment]
@MarcoSero, I'd suggest picking a rev that you know works for your app, then upgrade at your cadence. Maybe upgrade at the beginning of working on a version, or if you need a new feature we've added?

Bugs in this kind of framework are hard to find _generally_, but are best encountered when testing _actual apps_. As you can see, there isn't a lot of code in our example app, so we can't really test this in isolation. When we pull from github into the facebook app, we're obviously doing a lot more testing before pushing it to users, but it's only on the part used by that app.

We want to know as soon as possible if you have any issues caused by recent changes, so it's convenient if you upgrade frequently. Up to you. I'm sure we'll mark another version number soonish but I don't think it means anything more than a different commit on master.

**Comment by MarcoSero** [comment]
@darknoon you are right. Testing and reporting issues seem like the least we, users of the library, can do to contribute back to your work :+1:

**Comment by smiLLe** [comment]
closing this issue.
thanks for your feedback.
