### ISSUE TITLE
How to limit size of memory in Componentkit

### ISSUE THREAD

**Issue by ThanhTurin** [facebook/componentkit#358]
Hi guys,
In your example WildeGuess, everytime i scroll collectionview to bottom, the model will insert some items and the memory will increase too. If i want to limit the size of memory, how could i do that?

**Comment by ocrickard** [comment]
The framework assumes that the size of your models fits in memory easily and does not support paging model objects or components in and out of memory.

This means your model objects and components need to remain fairly small and stable in their memory footprint to support arbitrarily large lists of items.  NSObjects are not very big, so unless you are allocating literally hundreds of thousands or millions of them you're probably going to be OK with at least wrapper objects.  However, things get expensive when you start looking the data they contain.  If you have strong references to image buffers, sounds, fonts, text artifacts, etc, and they scale with the # of items in your list, then you're going to have to be smarter about how and when you take those references.

As an example of at least one way we have found effective for performance-critical high-memory-consumption objects:

TextKit allocates a very large amount of objects, buffers, and caches in order to lay out text, and can quickly add up to megabytes of memory for a small list view.  As a result CKTextKit operates through a global threadsafe LRU Cache.  So, you never actually hold onto text artifacts, instead you create a cache key that represents your data demands, and it uses the global write-through cache to either grab an already created one, or create a new one for you.  As a result of this system you can have many thousands of text labels in your scroll view, and thousands of representative Components and CoponentLayouts, but you will only ever have a finite number of actual glyph artifacts.

You can check out the cache here:

https://github.com/facebook/componentkit/blob/master/ComponentTextKit/TextKit/CKTextKitRendererCache.h#L94

And an example of how we use it here:

https://github.com/facebook/componentkit/blob/master/ComponentTextKit/CKTextComponent.mm#L37
