### ISSUE TITLE
Question: CKLabelComponent misaligned

### ISSUE THREAD

**Issue by lorixx** [facebook/componentkit#361]
`CKLabelComponent` does not round the text into pixel-aligned size, is that something expected?

I wonder if we could add a configurable attribute to it so that the text are aligned with respect to the pixel boundary. Otherwise text can be blurred.

**Comment by ocrickard** [comment]
Hmm, we do round to the pixel-aligned size:

https://github.com/facebook/componentkit/blob/master/ComponentTextKit/CKTextComponent.mm#L93

There is actually an issue with stack layouts that can cause the misalignment though due to how we distribute float math error.

Can you provide a little more information (code, snapshots, etc)?

**Comment by ocrickard** [comment]
If you can provide some more information (preferrably a snapshot test) that demonstrates this happening that would be very helpful.  Please re-open or file a new issue when you have more info!
