### ISSUE TITLE
CKLabelComponent flickers with frequent text changes

### ISSUE THREAD

**Issue by leoschweizer** [facebook/componentkit#396]
I have label component instances that update their text every second (think: timers). I don't do anything extraordinary with them:
````objectivec
[CKLabelComponent
	newWithLabelAttributes:{
		.string = ...,
		.font = [UIFont systemFontOfSize:16],
		.color = [UIColor ...]
	}
	viewAttributes:{}
]
```
Unfortunately, this leads to a clearly visible flickering on text changes. Is this working as designed, or is this a bug in the current ComponentKit release?

If I manually create UILabel instances instead, there is no visible flickering:
```objectivec
[CKComponent
	newWithView:{
		[UILabel class],
		{
			{@selector(setText:), ...}
		}
	}
	size:{
		.height = 21
	}
]
```

**Comment by ocrickard** [comment]
The reason this flickers is that we use asynchronous rendering in our label implementation.  This means that for large bodies of text as you scroll you don't stutter for the actual drawing of the glyphs.  UILabel renders synchronously on the main thread.

Internally for updates we create a parent view whose layer disables the async transaction for rapid model updates like this.

So, not a bug, feature.  We have a poorly documented bit of infrastructure you can use to disable the async transaction, but you probably don't want to do that since it's rather complex.  If your'e curious I can try to do a writeup later on how it works, don't ahve time right now.

If the label you're talking about isn't large, or the scroll performance of the view you're looking at isn't super crucial, just use UILabel as you describe.

**Comment by leoschweizer** [comment]
Allright, I'll stick with the UILabel route for now then!

**Comment by kevin0571** [comment]
I also notice that if I use +systemFontOfSize:weight instead of boldSystemFontOfSize: 
flicker happens every time even with small amount of text(less than 10 character) after I update the cell.
Any idea about why this happened?

**Comment by ocrickard** [comment]
The only reason this would be particularly bad for different fonts is if
that font is especially slow at sizing when compared with other fonts.

You can wrap your root views with transaction containers to prevent the
flickering.

On Thursday, December 24, 2015, Kevin Lin <notifications@github.com> wrote:

> I also notice that if I use +systemFontOfSize:weight instead of
> boldSystemFontOfSize:
> flicker happens every time even with small amount of text(less than 10
> character) after I update the cell.
> Any idea about why this happened?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/componentkit/issues/396#issuecomment-167145062>
> .
>


-- 
----------------------------------------------------------
Oliver Clark Rickard
ocrickard@gmail.com
(707) 536-1352
----------------------------------------------------------

**Comment by kevin0571** [comment]
Thanks for quick reply.
Will look into transaction container.

**Comment by kevin0571** [comment]
@ocrickard Just checked out *CKAsyncLayer*, found that if _needsAsyncDisplayOnly == YES, parent transaction container's displayMode will be ignored, as shown in:
https://github.com/facebook/componentkit/blob/38af8253af3c345a1d52fc0153002d4215442ba9/ComponentTextKit/Utility/CKAsyncLayer.mm#L138

And every time *CKTextComponent* is mounted, renderer of *CKTextComponentLayer* will be reset, and it calls setNeedsAsyncDisplay, as shown in:
https://github.com/facebook/componentkit/blob/38af8253af3c345a1d52fc0153002d4215442ba9/ComponentTextKit/CKTextComponentLayer.mm#L77

So far as I can see, *CKTextComponentView* will be rendered asynchronously anyway. Did I miss something? Please help to point out a way that I can force render *CKTextComponent* synchronously.
