### ISSUE TITLE
hello about the user interfaces smooth and responsive

### ISSUE THREAD

**Issue by wy19901227** [facebook/componentkit#409]
when I use componentkit, can it make the user interfaces smooth and responsive like AsyncDisplayKit
?

**Comment by ocrickard** [comment]
I worked a bit on both ASDK and ComponentKit.  I think we have done a pretty thorough comparison in public talks and in documentation, but briefly:

Yes and no.  ComponentKit by default will size and layout elements on background threads if you use the collection view and table view data sources.  This means the main thread is free for animations, scrolling, etc.  Some of the core components provided here also implement asynchronous drawing via async layers (CKTextComponent for example), this also helps with smooth scrolling.

However, ComponentKit is based on the React philosophy which makes complex interactive animations a little foreign to people used to UIKit animations.  They're possible, but due to the immutable nature of our pipeline they have to be done in a different way.  ASDK allows you to layout, size, and display off-main-thread, so provides the same type of free main-thread time that ComponentKit does.  Where it's different is that it's basically very similar to UIKit, and will be simpler for people used to working on iOS to write complex animations.

ComponentKit shines in highly complex codebases with diverse content types and many active contributors while maintaining smooth scrolling and a simpler model overall (React-ish) that encourages thread safety from the start.  ASDK provides the facilities for off-main-thread computation of UI state, but is not opinionated on how you design your threading model, so is easier to shoot yourself in the foot with.

**Comment by wy19901227** [comment]
did facebook peper use  AsyncDisplayKit
and facebook use componentKit?
