### ISSUE TITLE
UIImage thread safety

### ISSUE THREAD

**Issue by esam091** [facebook/componentkit#455]
It seems that `[UIImage imageNamed:]` is [not thread safe](http://stackoverflow.com/questions/26562317/load-uiimage-in-background-thread), and iirc components are created in background thread. To make it thread safe, I have to load the images first and then pass them through the context. It would be better if we have something like `[CKImageComponent newWithImage: [LazyLoadedImage imageNamed:@"image"]]` that takes care of the image loading on the main thread. Or maybe thread safety isn't a problem at all? I don't know.

**Comment by ocrickard** [comment]
Definitely, this is something we've struggled with for a long time, and isn't unique to ComponentKit. In iOS 9 I believe in practice (and documented) we *have* found that UIImage imageNamed: is threadsafe on iOS 9+, but you're right that we need workarounds for versions prior to this. The approach we used is to preload and hit an in-memory cache on bg threads.

I don't think that we should make any commits to core component kit since it's been fixed by Apple in recent versions, but it's a great candidate for an open-source microlibrary if you build a preloading solution!

**Comment by esam091** [comment]
The only thing that bothers me with this preloading approach is that I have to specify what images I want to preload, and not to forget to keep track of what images are changed in the component every time we need to change assets. Any suggestions on this @ocrickard ?

**Comment by ocrickard** [comment]
Yeah, totally agree it's not great. We pre-load all the ones we know are hit often, and then we (in an extremely careful way), bounce to the main thread to load images synchronously in component creation if they haven't been pre-loaded. The thread switch is really dangerous and we had tons of code review to make sure it wouldn't deadlock... but it does work for the cases where you forget to add a file to the preload list.

An alternative to this is to create your own component with a component controller or view which actually loads the images for you on the main thread. All component controller methods are main-thread affined so you should be fine loading the image in didMount or something (so long as you clean up after yourself), and then loading and setting the image on the component's view manually.

Of course the problem with this approach is that you don't know the image's size in the component layout phase without the actual image (since layout is off-main). So you probably need a different storage layer for your sizing information. We had talked about having a code-gen step inspect the binary for images or asset catalogs and record their sizes into a manifest (either into compiled structs or a plist file or something) so the size is available in layout. Then on main when your layer asks for the data you can lazily load in the images you need.

But, we never built such a system since the thread trampoline worked well enough and Apple fixed the problem in iOS 9.

**Comment by esam091** [comment]
I'll go with the old way I think, since it's the simplest way to go for now. Those are good ideas but we don't have the resources for now. Thanks alot :)
