### ISSUE TITLE
CKViewComponentAttributeValueMap being unordered can cause issues

### ISSUE THREAD

**Issue by conradev** [facebook/componentkit#461]
Because the `CKViewComponentAttributeValueMap` is unordered, the value in the below example can be set before the maximum value is set, and the default maximum value is `100`. So, in this case, if value is set to `150` while the maximum value is still `100`, it gets normalized to `100`.

``` objc
[CKComponent
newWithView:{
    [UIStepper class],
    {
        {@selector(setMaximumValue:), @200},
        {@selector(setValue:), @150},
    }
} size:{}]
```

Thoughts on turning `CKViewComponentAttributeValueMap` into an ordered map?

**Comment by ocrickard** [comment]
In general we view requiring a specific sequence of mutable calls in order to guarantee correct behavior as a bit too fragile -- it will eventually break. That being said in this case it sounds like you can't control the view class (UIStepper) to harden its behavior. Instead we have some workarounds you could probably use for this case:

1. Use a custom attribute applicator. I believe we allow a block to be used to set and unset values on your view. You could use a block to set the values on your view in exactly the ordering you need.
2. In your component implement the mounting function and apply your setters in the order that you want.

I think that we would prefer to keep the map unordered so that:

```
{ {@selector(setA:), @"a"}, {@selector(setB:), @"b"} }
```
and
```
{ {@selector(setB:), @"b"}, {@selector(setA:), @"a"} }
```
are not identified as two different attribute maps, forcing an attribute application when one isn't needed for the vast majority of cases.

**Comment by ocrickard** [comment]
Closing this out. Feel free to reopen if the workarounds don't work as advertised!

**Comment by conradev** [comment]
Makes sense, thanks! I'll use a block applicator for this particular case.
