### ISSUE TITLE
Ignore touches for text which is not "clickable link"

### ISSUE THREAD

**Issue by vbadeasv** [facebook/componentkit#472]
Hi all,

I have the following case:
- A list of Twitter tweets displayed in a UICollectionView.
- The tweet's content is displayed using CKTextComponent (the URLs inside tweet's content  are made clickable via CKTextKitEntityAttributeName)
- I want to open a Safari controller whenever the user taps a URL, but when he **taps non URL text** to let the CollectionView to select the cell so to be able to push a ViewController.   

My question:
- Is there a cleaner/recommended way of ignoring CKTextComponent touch events when they do not occur on a link, so to let the row become selected?

At this point I have the following hack (works OK but I don't quite like it):
- In a category over CKTextComponentView, which resides in my app, I implemented hitTest:point withEvent: like this:
```
@implementation CKTextComponentView(Hacks)
- (UIView*)hitTest:(CGPoint)point withEvent:(UIEvent *)event {
    UIView *hitView = [super hitTest:point withEvent:event];
    // If there is no link at touching point then just lie that no view is clicked.
    // This will cause the touches to be delivered to superview, and in our case
    // most likely will hit the table/collection cell thus causing the selection
    // of that cell.
    if (hitView == self && ![self.renderer textCheckingResultAtPoint:point]) {
        return nil;
    } else {
        return hitView;
    }
}
@end
```
- The reason why I have a category is to not "dirty" the ComponentKit code by adding my code inside CKTextComponentView.mm and also I didn't want to create my custom  CKTextComponent/CKTextComponentView just for this.

**Comment by ocrickard** [comment]
Yes, we basically do the same thing internally for Feed, so your solution is correct. I think you're better off duplicating and customizing CKTextComponentView as a separate library to achieve this, and probably not implement it in a category (but obviously that's up to you). I don't want to override hitTest by default in the core library because it has lots of implications (and headaches) for normal use-cases and debugging. We learned this since we originally *did* have this behavior in the core text view and it caused lots of problems for people.

**Comment by vbadeasv** [comment]
Thanks @ocrickard. Probably I'll end up with a custom conponent in a separate library because I have some other changes/additions to ComponentKit.
