### ISSUE TITLE
How to handle rotations

### ISSUE THREAD

**Issue by 7ynk3r** [facebook/componentkit#56]
The component kit is amazing! The amount of code is nothing compared with the traditional.

I'm trying to figure out how to handle rotations. Because all view has to be updated, I would need to update all the models. This works as long as the amount is not big (>100). 
Any ideas on this? BTW, I noticed that facebook app for iOS doesn't support rotations.

**Comment by benlodotcom** [comment]
Sorry for the delay getting back to you.

> Because all view has to be updated, I would need to update all the models
Yes or at least they will eventually need to be before they come on screen.

We currently don't have infrastructure to handle rotation in other ways that updating all the models.
But if you want to tackle it, here are a few different approaches that you could pursue :
- For your components always compute a landscape and portrait version and switch between them.
- Recompute only a subset of what is visible synchronously, and start the recomputation of others asynchronously. In your datasource when you're about to show a new cell verify the right layout has been recomputed and otherwise enqueue a synchronous recompute/just wait until the async recomputation is done.

This could be a great addition to the datasources ! Let me know if you need more info.

**Comment by 7ynk3r** [comment]
Thanks for the response! 

I'll try the approaches you mentioned and let you know.

**Comment by nihalahmed** [comment]
@7ynk3r Hey, I am facing a similar issue as you have, and was wondering if any of the above suggestions helped you? I am quite new to ComponentKit. I am not sure how to do a relayout as suggested above. @benlodotcom If you could also guide me how to do that, I would appreciate it.

**Comment by 7ynk3r** [comment]
I end up doing reloading the list after rotation it. The problem is that if the list is long it can take a little time.
