### ISSUE TITLE
Question - Best practice for error handling

### ISSUE THREAD

**Issue by avnerbarr** [facebook/componentkit#585]
Since the component's root is updated through a class method and asynchronously in some cases, I am curious about the best way to handle errors while building a component hierarchy.

I came across a situation where the error only appears when returning the root component (one of the components can "throw" an error derived from an illegal model).

For instance in the case below:
```
// view controller
- (void)viewDidLoad {
...
_ckView = [[CKComponentHostingView alloc] initWithComponentProvider:[self class]
                                                      sizeRangeProvider:_sizeRangeProvider];
...
[_ckView updateModel:viewModel mode:CKUpdateModeSynchronous]; 
}

// the callback:
#pragma mark - CKComponentProvider

+ (CKComponent *)componentForModel:(Model *)model context:(ComponentContext *)context {
.... // setup code ...
CKComponent *rootComponent = [MyCKRootComponent rootComponent:model context:context]; // have an error in the model and the component is nil
    if (!rootComponent) {
        Log(@"-E- This is a criticial error. Could not build a root component for model %@",model);
        // suggested way to stop the flow? 
       // need to return "nil" root component
    }
   ....
   return rootComponent;
}
```

**Comment by adamjernst** [comment]
You could return a dummy empty component perhaps? I'm not sure quite what you're asking… do you want it to be a truly fatal error or not?

**Comment by avnerbarr** [comment]
In my particular case, each component validates its input model , (for instance a component which loads a network image may be unreachable).

It makes sense in some cases that the component constructor fail and return a "nil" component (representing an error). 

It wouldn't make sense to display an empty image component as it could render the UI unusable. 

Ideally I could bail out of the `CKComponentProvider` callback, i.e. return a nil component in `componentForModel:context:` (That causes a crash). 

Since the delegate is defined a class method, it becomes difficult to communicate back to the actual instance which owns the state (i.e. a view controller managing the `CKComponentHostingView` that called `_ckView updateModel:context:`) . 

I think that the view controller in this case should be able to handle any errors and possibly decide on returning a dummy component

Maybe I could rephrase the question to "how can I cancel a call to "`updateModel:context` so that I don't get an exception"?

**Comment by eczarny** [comment]
@avnerbarr I think generally you would want to build the resilience further down the stack. In your example if the image cannot be downloaded from the network you would likely want to display some placeholder (perhaps with the potential to retry).

If you encounter a critical failure that cannot be recovered I'd say let the app crash. If it's truly irrecoverable there really isn't anything you can do. You could also try and move your model validation closer to where you attempt to update the component hierarchy; in your original example this would be in the view controller.

> Since the delegate is defined a class method, it becomes difficult to communicate back to the actual instance which owns the state (i.e. a view controller managing the CKComponentHostingView that called _ckView updateModel:context:) .

This is by design. If the component provider were an instance method it would be far easier to accidentally access, or mutate, state across a thread boundary.
