### ISSUE TITLE
How to work with a gif animation or video in ComponentKit? Does anyone have an example?

### ISSUE THREAD

**Issue by IrixVol** [facebook/componentkit#607]

**Comment by ocrickard** [comment]
Since ComponentKit allows you to interact directly with UIViews, this is as easy as wrapping views that hold animated gifs or video players.

Check our docs for configuring views:

http://componentkit.org/docs/views.html
http://componentkit.org/docs/advanced-views.html

One thing I will note for complex views like gifs and videos is that the views themselves tend to be very heavy, and need to be reused for the same cell when updating the collection view to avoid stutters in the animations or playback. Generally when we do this internally, we actually use "stateful views"

https://github.com/facebook/componentkit/blob/master/ComponentKit/StatefulViews/CKStatefulViewComponentController.h
