### ISSUE TITLE
CKCollectionViewDataSource: number of sections and items in section

### ISSUE THREAD

**Issue by MarcoSero** [facebook/componentkit#64]
Is there a reason why `CKCollectionViewDataSource` doesn't expose 

```objective-c
- (NSInteger)numberOfSections;
- (NSInteger)numberOfObjectsInSection:(NSInteger)section;
```

the same way `CKComponentDataSource` does?

Or maybe it could expose that it implements `UICollectionViewDataSource`?

I'd probably prefer the same interface as `CKComponentDataSource`, since implementing `UICollectionViewDataSource` is just an implementation detail.

**Comment by benlodotcom** [comment]
These pieces of state are always in sync with the collectionView and they are exposed on `CKComponentDataSource` because it is needed to implement the `UICollectionViewDataSource` protocol. 

I'm not sure we should expose it at the `CKCollectionViewDataSource` layer as it would leak some implementation details, is there something preventing you to query it from the collectionView ?

**Comment by MarcoSero** [comment]
That makes perfectly sense :+1: 
Will query the collection view.
