### ISSUE TITLE
Question - what is the difference between sync and async mode in CKComponentHostingView updateModel

### ISSUE THREAD

**Issue by avnerbarr** [facebook/componentkit#713]
I'm assuming that the layout calculations are always performed in background threads (Is this correct?) and that sync pertains to "blocking" the caller until layout has been performed. 

Is this correct? I couldn't verify for sure. I am not getting callbacks  for CKComponentHostingViewDelegate in any case .

(Also in reference to issue: https://github.com/facebook/componentkit/issues/711)

**Comment by conradev** [comment]
Synchronous mode means that the layout is calculated and subsequently mounted on the main thread "immediately" (technically I think it may happen in the next tick of the run loop), and asynchronous mode means the layout is calculated on a background thread and then mounted on the main thread upon completion.

I'm not sure why #711 would be happening, but if you look at the code path for `-[CKComponentHostingView updateModel:mode:]`, it very directly calls the delegate, so that is weird!

**Comment by avnerbarr** [comment]
Does the sync mode block the main thread for calculatung? What would be the advantage of using sync mode?

**Comment by eczarny** [comment]
> Synchronous mode means that the layout is calculated and subsequently mounted on the main thread "immediately" (technically I think it may happen in the next tick of the run loop), and asynchronous mode means the layout is calculated on a background thread and then mounted on the main thread upon completion.

@conradev is correct. The transactional data source does in fact compute the layout and mount the component hierarchy on the main thread in the next tick of the runloop.

> Does the sync mode block the main thread for calculatung?

It does, just not immediately when issuing a state update synchronously (due to the work being done on the next tick of the runloop, as mentioned above).

> What would be the advantage of using sync mode?

Usually when you what to issue a state update in response to a user interaction. Anything that requires a more immediate change. In general though you usually want to use the asynchronous mode as it is better for performance (particularly while scrolling to avoid dropping any frames).

**Comment by eczarny** [comment]
Closing this issue out for now. @avnerbarr please reopen if your question hasn't been answered. I'll follow up on #711 separately.
