### ISSUE TITLE
Question - Modifying a component using a gesture - Proper way to do this

### ISSUE THREAD

**Issue by avnerbarr** [facebook/componentkit#98]
I want to implement the "pan to reveal" auxiliary actions seen in the mail app. ("Delete","Archive"...)
Reading the responder chain doc:
*"Drop down and mutate the underlying views directly as the user performs a gesture."*

Not sure what exactly I should be mutating , and not sure if the state is saved if the user scrolls.
State meaning the new appearance of the view that was mutated.

For instance:
```objective-c
+(instancetype)newWith.... {
....
....
    CKBackgroundLayoutComponent *background = [CKBackgroundLayoutComponent newWithComponent:stack background:[CKComponent newWithView:{
        [UIView class],
        {
            {
                @selector(setBackgroundColor:),[UIColor whiteColor]
            },
            {CKComponentViewAttribute::LayerAttribute(@selector(setCornerRadius:)), @4.0},
            {shadow,[UIColor blackColor]},
            **{CKComponentPanGestureAttribute(@selector(didPan:gesture:))}**

            
        }
    }size:{}]];
...
...
return [super newWithComponent:...];
```

I added the gesture to the background view of the component (Not sure if this is the suggested way)

Also not sure what happens to the background's view "Subviews" - ( sub components).

This isn't giving any sort of result I would want:
```objective-c
-(void)didPan:(CKComponent *)component gesture:(UIPanGestureRecognizer *)gesture {
    CGRect frame = component.viewContext.frame;
    frame.origin.x += [gesture translationInView:gesture.view.superview].x;
    gesture.view.frame = frame;
    [gesture setTranslation:CGPointZero inView:gesture.view.superview];
}
```

Thanks!

**Comment by kastiglione** [comment]
> not sure if the state is saved if the user scrolls. State meaning the new appearance of the view that was mutated.

It's necessary to have some code for tracking the view mutations made outside of the scope of Components. [Component Controllers](http://componentkit.org/docs/component-controllers.html) is one way to do this.

I'm not sure what the exact problems you're referring to are, but this line will be the source of some problems:

```objc
frame.origin.x += [gesture translationInView:gesture.view.superview].x;
```

`-translationInView:` doesn't provide a delta since the last gesture update, it's the *total* translation since the beginning of the pan gesture. Apple's docs say:

> do not concatenate the value each time the handler is called.

If `-didPan:gesture:` is moved to the component controller, then that controller can maintain the state being changed in the gesture (and any other non-Component state). The controller can also capture the starting point, and then, when the gesture handler is called with `state == UIGestureRecognizerStateChanged`, the controller can update the `x` based on the starting `x` and the translation `x`.

```objc
frame.origin.x = self.startingPoint.x + [gesture translationInView:gesture.view.superview].x;
```

**Comment by avnerbarr** [comment]
I had a bug-o .
I should have also set the translation to zero after setting the offset of the view.

I guess my question is more general. 
As I am building component hierarchies as opposed to view hierarchies, I'm not sure which view should get the gesture attached to it.

And since the view is re-used, I don't know how the state should be saved.

Is there an example of using gestures I could reference against?

**Comment by avnerbarr** [comment]
The videos in the FB feed can be dragged around - I think its a pretty similar case

**Comment by mbrgm** [comment]
I would also be interested in this.

**Comment by darknoon** [comment]
You want to keep around any necessary state in your controller (which will get the gesture actions via the responder chain). You can then apply any state to the view when it's mounted. This will preserve it across remounts, and you can re-apply to any new view that is mounted.

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by darknoon** [comment]
Did you try our suggestion? Going to close if there isn't anything concrete we can answer.
